# Generated by Django 4.2.7 on 2023-12-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='receipt_photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/receipt_photo /'),
        ),
    ]
