# Generated by Django 4.2.7 on 2024-01-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reply_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='TicketReply',
        ),
    ]
